export const CONNECTION_STATUSES = Object.freeze({
  STOPPED: 'STOPPED',
  STARTING: 'STARTING',
  WAITING: 'WAITING FOR ANALYZER',
  CONNECTED: 'CONNECTED',
  DATA_RECEIVED: 'DATA RECEIVED',
  ERROR: 'ERROR',
});

export const PROCESSING_STATUSES = Object.freeze({
  RECEIVED: 'RECEIVED',
  PARSED: 'PARSED',
  MATCHED: 'MATCHED',
  UNMATCHED: 'UNMATCHED',
  DUPLICATE: 'DUPLICATE',
  ERROR: 'ERROR',
});
