export const LAB_TESTS_DATA = {
  "CBC": { name: "CBC", machine: ["Cell Counter Analyzer"], normalRange: "", mrp: 250, unit: "" },
  "PCT": { name: "PCT", machine: ["Cippoint"], normalRange: "", mrp: 0, unit: "" },
  "BSR": { name: "BSR", machine: ["Biochemistry Analyzer"], normalRange: "80-140", mrp: 50, unit: "mg/dl" },
  "CRE (Creatinine)": { name: "CRE (Creatinine)", machine: ["Biochemistry Analyzer"], normalRange: "0.4-1.5", mrp: 100, unit: "mg/dl" },
  "UREA": { name: "UREA", machine: ["Biochemistry Analyzer"], normalRange: "15-45", mrp: 100, unit: "mg/dl" },
  "URIC ACID": { name: "URIC ACID", machine: ["Biochemistry Analyzer"], normalRange: "3.4-7.0", mrp: 100, unit: "mg/d" },
  "CALCIUM": { name: "CALCIUM", machine: ["Biochemistry Analyzer"], normalRange: "8.8-10.5", mrp: 150, unit: "mg/dl" },
  "ELC (Electrolytes)": { name: "ELC (Electrolytes)", machine: [], normalRange: "NA-135-155, K-3.5-5.5, Chl-99-108", mrp: 500, unit: "" },
  "LFT": { name: "LFT", machine: ["Biochemistry Analyzer"], normalRange: "Tbil-0-1.0, Dbil-0-0.3, Indirect bil 0-0.8", mrp: 600, unit: "" },
  "RFT": { name: "RFT", machine: ["Biochemistry Analyzer"], normalRange: "", mrp: 500, unit: "mg/dl" },
  "PT INR": { name: "PT INR", machine: [], normalRange: "14", mrp: 300, unit: "Seconds" },
  "APTT": { name: "APTT", machine: [], normalRange: "14", mrp: 300, unit: "Seconds" },
  "LIPID PROFILE": { name: "LIPID PROFILE", machine: ["Biochemistry Analyzer"], normalRange: "", mrp: 500, unit: "mg/dl" },
  "URINE R": { name: "URINE R", machine: [], normalRange: "", mrp: 100, unit: "" },
  "HIV": { name: "HIV", machine: ["Serology Analyzer"], normalRange: "Negative", mrp: 250, unit: "" },
  "HbsAg": { name: "HbsAg", machine: ["Serology Analyzer"], normalRange: "Negative", mrp: 250, unit: "" },
  "HCV": { name: "HCV", machine: ["Serology Analyzer"], normalRange: "Negative", mrp: 450, unit: "" },
  "DENGUE IgG IgM NS1": { name: "DENGUE IgG IgM NS1", machine: ["Serology Analyzer"], normalRange: "Negative", mrp: 1000, unit: "" },
  "MALARIA (SPOT)": { name: "MALARIA (SPOT)", machine: ["Serology Analyzer"], normalRange: "Negative", mrp: 300, unit: "" },
  "CPK-MB (MASS)": { name: "CPK-MB (MASS)", machine: ["Finecare Analyzer"], normalRange: "0-5", mrp: 500, unit: "ng/ml" },
  "TROP I": { name: "TROP I", machine: ["Finecare Analyzer"], normalRange: "0.0-0.3", mrp: 1000, unit: "ng/ml" },
  "CHICKENGUNEA": { name: "CHICKENGUNEA", machine: ["Serology Analyzer"], normalRange: "Negative", mrp: 800, unit: "" },
  "WIDAL": { name: "WIDAL", machine: ["Slide Analyzer"], normalRange: "", mrp: 150, unit: "" },
  "RA": { name: "RA", machine: ["Biochemistry Analyzer"], normalRange: "", mrp: 350, unit: "IU/ml" },
  "HbA1C": { name: "HbA1C", machine: ["Finecare Analyzer"], normalRange: "", mrp: 500, unit: "" },
  "AMYLASE": { name: "AMYLASE", machine: ["Biochemistry Analyzer"], normalRange: "30-90", mrp: 500, unit: "mg/dl" },
  "LIPASE": { name: "LIPASE", machine: ["Biochemistry Analyzer"], normalRange: "5-60", mrp: 600, unit: "mg/dl" },
  "C\\S URINE (Culture)": { name: "C\\S URINE (Culture)", machine: [], normalRange: "", mrp: 600, unit: "" },
  "PSA": { name: "PSA", machine: [], normalRange: "", mrp: 750, unit: "" },
  "TFT": { name: "TFT", machine: [], normalRange: "", mrp: 500, unit: "" },
  "FREE TFT": { name: "FREE TFT", machine: [], normalRange: "", mrp: 700, unit: "" },
  "TPO (Antibody)": { name: "TPO (Antibody)", machine: [], normalRange: "", mrp: 1250, unit: "" },
  "ANA Blot": { name: "ANA Blot", machine: [], normalRange: "", mrp: 3300, unit: "" },
  "Vit-B12": { name: "Vit-B12", machine: [], normalRange: "", mrp: 1200, unit: "" },
  "NT Pro-BNP": { name: "NT Pro-BNP", machine: ["Immunoassay Analyzer"], normalRange: "", mrp: 2500, unit: "" }
};
